### PR TITLE
Add: Ultima Dark theme

### PR DESCRIPTION
**Pull request by egorlem**
I would like to add a file with my color scheme

ultima

Thanks in advance

### CODE REVIEW

**Review by chrisduerr — CHANGES_REQUESTED** [review]
> with my color scheme

The litmus test for adding new themes is not having the author of the theme submit it. That way there's at least two people interested in the theme.

It makes no sense to add every individual theme people use.

**Comment by egorlem** [comment]
Where is this written?

Your 'To add a new theme, just create a Pull Request with the following changes:' is misleading. Please indicate this in your contribution guide. So that people don't waste their time and don't useless pull requests

**Comment by chrisduerr** [comment]
> Where is this written?

I would assume it to be common sense. Apparently not common enough. There's really no logical reason why we'd just add every random theme out there.

**Comment by egorlem** [comment]
Only one reason — community. Even if it's complete crap. In general, I understood you. I can conclude that the author of alacritty is`t very friendly with his community. 

Good luck

**Comment by kchibisov** [comment]
>Only one reason — community. Even if it's complete crap. In general, I understood you. I can conclude that the author of alacritty is`t very friendly with his community.

If you accept a theme from author directly, it means that you can write a new theme every day and submit upstream, which doesn't make any sense and can be easily abused. So the theme should be at least somehow known and submitted by not the author directly.

Confusing friendliness with "not letting abuse to happen" is unfortunate.

**Comment by egorlem** [comment]
> > Only one reason — community. Even if it's complete crap. In general, I understood you. I can conclude that the author of alacritty is`t very friendly with his community.
> 
> If you accept a theme from author directly, it means that you can write a new theme every day and submit upstream, which doesn't make any sense and can be easily abused. So the theme should be at least somehow known and submitted by not the author directly.
> 
> Confusing friendliness with "not letting abuse to happen" is unfortunate.

I understand perfectly what you are talking about and I wholeheartedly agree with you. Write this in the contribution guide. Write from whom you accept pr and define what it means popular theme and we won't create a pr and won't receive comments that we are trying to push a 'random' theme. Popular is how much? 1k 5k 10k 50k stars 

> > Where is this written?
> 
> I would assume it to be common sense. Apparently not common enough. There's really no logical reason why we'd just add every random theme out there.

My theme isn't 'random' for me. It sounded offensive. "You're not popular enough, you can't come here." That's what I heard

We can correspond here forever. Just define the rules in the readme

**Comment by egorlem** [comment]
Or do the same as Robbie Russell did for oh-my-zsh - just closed accepting user themes. 
He put it all on the wiki and everyone lives happily. 

We are discussing here who is worthy of merge to main and who is not. It's very thin ice

**Comment by kchibisov** [comment]
The point is not what we merge, but who sends the patch to propose some theme. If the person is involved with the project then likely not, if it's some 3rd party than it's fine.

It's the same if I wanted to e.g. promote alacritty and start sending PR to every _curated list of things_ myself, because I'm _biased_, the same way as you're _biased_. The point is always not _starts_ or some other social network aspect, but _bias_.

If other person not associated with your project submitted it, then it'll likely be fine, because it's not you submitting it, but someone not associated with your project.

And as @chrisduerr said, it's fairly a common sense, even in real life outside of software (e.g. recommendations, etc).

**Pull request closed without merging**
