### PR TITLE
Add dos theme

### PR DESCRIPTION
**Pull request by medo64**
This adds theme with quite straightforward, old-style definitions for colors where each color has the same numerical value and brights sit at 100% of their value.

### CODE REVIEW

**Comment by chrisduerr** [comment]
What's the source of this theme?

**Comment by medo64** [comment]
Not sure I understand the question. If you are inquiring about source link, there is none really since this theme was created manually and thus no external source exists (e.g. like chicago95 doesn't have one).

**Comment by chrisduerr** [comment]
We don't add themes that are self-created, because there's no evidence anyone actually is interested in them.

**Comment by medo64** [comment]
Fair enough.

**Pull request closed without merging**
