### PR TITLE
Add the colorscheme emulating MSX

### PR DESCRIPTION
**Pull request by avysk**
See https://en.wikipedia.org/wiki/MSX

Color values are coming from
https://paulwratt.github.io/programmers-palettes/HW-MSX/HW-MSX-palettes.html

### CODE REVIEW

**Review by chrisduerr — CHANGES_REQUESTED** [review]
Why is this called MSX-like? Would make much more sense to just call it MSX imo.

Is this a theme you've copied from somewhere else or did you write this yourself?

**Comment by avysk** [comment]
I can rename it. I did not copy or convert it from anywhere, I did write it myself. The values for the colors are taken from the indicated web page.

**Comment by chrisduerr** [comment]
Please do, if the goal is to emulate MSX I think the "-like" suffix is just confusing.

**Comment by avysk** [comment]
I have renamed it.

**Review by chrisduerr — APPROVED** [review]

**Pull request merged**
